name: Go

on:
  push:
    branches: [ main, github-actions ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
#    - name: Install libusb
#      run: sudo apt-get install -y libusb-1.0-0-dev
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
#    - run: find /home/runner -type f
#    - name: Upload build artifact
#      uses: actions/upload-artifact@v2.3.1
#      with:
#        name: wInd3x-linux
#        path: ./wInd3x
